### PR TITLE
CI: update to latest standards

### LINKED ISSUE #61: Update to latest shared CI scripts
## Expected Behavior
Use newest, shared CI scripts.

## Current Behavior
Using older style. Unable to automatically deploy to PyPI.

### PR DESCRIPTION
**Pull request by klauer**
## Description
Update to latest CI standards.

## Motivation and Context
Closes #61 
With PYPI_TOKEN now set, we can deploy to PyPI as well.

### CODE REVIEW

**Review by ZLLentz — APPROVED** [review]

**Comment by ZLLentz** [comment]
shame about the pypi testing segfault
as if we'll reproduce that ever

**Comment by klauer** [comment]
Docs build failing with:
```
Warning, treated as error:

/home/travis/build/pcdshub/pcdswidgets/docs/source/icons.rst:23:image file not readable: _static/icons/RoughGaugeSymbolIcon.png
```

**Comment by hhslepicka** [comment]
Docs are failing because this step is not being executed: `      python examples/show_icon.py	`
I'm not sure how we can add a hook up for a pre-docs command to be run.
Maybe we can change the Makefile inside of the docs folder so it becomes part of the `make html`?

**Comment by hhslepicka** [comment]
Here is a possible fix to the docs issue: #63 
Feel free to use or trash it if you have another plan/idea.

**Review by hhslepicka — CHANGES_REQUESTED** [review]
The docs build is broken as discussed above... #63 is a suggestion of possible fix... if that is an acceptable fix, we can merge it and rebase this PR so docs build properly again. Otherwise a new strategy will be needed.

**Comment by klauer** [comment]
👍 Looks like that did it.

**Review by hhslepicka — APPROVED** [review]

**Comment by hhslepicka** [comment]
LGTM

**Pull request merged**
