### PR TITLE
ENH: Normally Open Pneumatic Valve Widget

### LINKED ISSUE #59: New Widget Pneumatic Valve with Readback Normally Open
TMO has pneumatic valves installed that are normally open with limits switch readback, and we need a new widget for them.
## Expected Behavior
The behavior of this widget is similar to the that of a pneumatic valve. The difference is that it is commanded to close instead of commanded to open.
image

### PR DESCRIPTION
**Pull request by hhslepicka**
## Description
Normally Open Pneumatic Valve Widget

## Motivation and Context
Closes #59 

## How Has This Been Tested?
Locally

## Where Has This Been Documented?
Documentation was included in this Pull Request

## Screenshots (if appropriate):
image

### CODE REVIEW

**Comment by hhslepicka** [comment]
Attn. @ghalym I need you to confirm please the Ophyd Expert Screen for this Widget.
It is currently using the same as the Pneumatic Valve which I believe won't work properly.

**Comment by ZLLentz** [comment]
This looks good to me, though I laughed uncontrollably imagining a random beamline valve just saying "No". It's a Monday.

**Comment by hhslepicka** [comment]
@ZLLentz I should have called it the `Denial Valve`

**Comment by ghalym** [comment]
@hhslepicka This widget should use the VVCNO Ophyd object.

**Comment by hhslepicka** [comment]
@ghalym thank you for confirming.
@ZLLentz I believe this is good for a review/merge once CI passes.

**Review by ZLLentz — APPROVED** [review]
This looks good to me, though I am not well-versed in this repo's base classes so it's possible to miss something

**Comment by hhslepicka** [comment]
Thanks for the review and merge, @ZLLentz!

**Pull request merged**
